### ISSUE TITLE
'show' emulator does not work in 'terminology'

### ISSUE THREAD

**Issue by raboof** [polyfloyd/ledcat#10]
The emulator works fine in xterm, but not in the 'terminology' terminal. Might of course be a terminology issue, haven't dug into the cause of the issue yet.

**Comment by polyfloyd** [comment]
It seems to work fine for me with Terminology from Debian Sid although it's a bit slow.

Could you provide some more details:
* What command did you used to run Ledcat?
* What were you expecting to happen?
* What happened instead?
* Anything else that might help to reproduce the issue?

**Comment by raboof** [comment]
turns out I was running an ancient version of terminology, seems fine now.. sorry :)
