### ISSUE TITLE
Can’t get more than 1 LED light activating on a 144 LED SK9822 strip

### ISSUE THREAD

**Issue by alandao** [polyfloyd/ledcat#14]
Not sure if this project is still being worked on, but the title is self explanatory. I’ve tried various commands below and I can only get the 1st LED to change color.
```
perl -e 'print "\xff\x00\x00" x 30' | ledcat --geometry 9 sk9822 > /dev/spidev0.1

perl -e 'print "\xff\x00\x00" x 30' | ledcat --geometry 144 sk9822 > /dev/spidev0.1
```

**Comment by polyfloyd** [comment]
Hi! I am dropping SPI controlled devices from the scope of this project in its entirety in favour of pointing people to use an ESP32 with WLED: https://github.com/Aircoookie/WLED

This is because WLED is much more mature than Ledcat and testing SPI with actual hardware is too elaborate.
