### ISSUE TITLE
DeviceNotSupported for spidev0.0

### ISSUE THREAD

**Issue by BonaBeavis** [polyfloyd/ledcat#48]
I can control the led stripe with https://github.com/jgarff/rpi_ws281x. But ledcat fails with:
```
Error: DeviceNotSupported
```

The command was `perl -e 'print "\xff\x00\x00" x 30' | ledcat --geometry 30 --driver spidev -o /dev/spidev0.0 ws2812`

**Comment by polyfloyd** [comment]
Hi! Thank you for reporting this. Unfortunately, it is quite hard to debug issues like this as I often do not have the appropriate hardware. I'll look into this when I have time. If I can debug this without hardware it should be possible to fix
